### PR TITLE
Set up Bugsnag on the frontend and backend

### PR DESCRIPTION
**Pull request by pepibumur**
- [x] Add Bugsnag to the frontend and backend
- [ ] Set up Vite to read the Bugsnag frontend key from the environment.
- [ ] Add a Rake task to upload the generated sourcemaps to Bugsnag

### CODE REVIEW

**Comment by ElMassimo** [comment]
Hi Pedro, here's a patch related to https://github.com/ElMassimo/vite_ruby/discussions/58 and https://github.com/ElMassimo/vite_ruby/discussions/59.

There's a bug in `@vite/plugin-react-refresh` where file paths don't match when using `@fs` imports (files outside Vite's root). I'll open an issue shortly.

```patch
diff --git a/projects/app/app/helpers/vite_helper.rb b/projects/app/app/helpers/vite_helper.rb
new file mode 100644
index 0000000..70fae31
--- /dev/null
+++ b/projects/app/app/helpers/vite_helper.rb
@@ -0,0 +1,18 @@
+# frozen_string_literal: true
+
+module ViteHelper
+  def vite_react_refresh_tag
+    return unless ViteRuby.instance.dev_server_running?
+
+    <<~PREAMBLE.html_safe
+    <script type="module">
+      import RefreshRuntime from "http://localhost:3000/@react-refresh"
+      RefreshRuntime.injectIntoGlobalHook(window)
+      console.log({ RefreshRuntime })
+      window.$RefreshReg$ = () => {}
+      window.$RefreshSig$ = () => (type) => type
+      window.__vite_plugin_react_preamble_installed__ = true
+    </script>
+    PREAMBLE
+  end
+end
diff --git a/projects/app/app/javascript/components/App.tsx b/projects/app/app/javascript/components/App.tsx
deleted file mode 100644
index 1d13680..0000000
--- a/projects/app/app/javascript/components/App.tsx
+++ /dev/null
@@ -1,13 +0,0 @@
-import React from "react";
-import ErrorTracking from "./ErrorTracking";
-
-const App = () => {
-  // @ts-ignore
-  return (
-    <ErrorTracking>
-      <div>Hello worldssgs;</div>
-    </ErrorTracking>
-  );
-};
-
-export default App;
diff --git a/projects/app/app/javascript/entrypoints/application.tsx b/projects/app/app/javascript/entrypoints/application.tsx
index 8bd1652..e029913 100644
--- a/projects/app/app/javascript/entrypoints/application.tsx
+++ b/projects/app/app/javascript/entrypoints/application.tsx
@@ -1,5 +1,16 @@
 import React from "react";
 import ReactDom from "react-dom";
-import App from "../components/App";
+
+import ErrorTracking from "../components/ErrorTracking";
+
+const App = () => {
+  // @ts-ignore
+  return (
+    <ErrorTracking>
+      <div>Hello world...</div>
+    </ErrorTracking>
+  );
+};
+
 
 ReactDom.render(<App />, document.getElementById("react-app"));
diff --git a/projects/app/app/views/layouts/application.html.erb b/projects/app/app/views/layouts/application.html.erb
index 7d77963..e2a71f5 100644
--- a/projects/app/app/views/layouts/application.html.erb
+++ b/projects/app/app/views/layouts/application.html.erb
@@ -6,6 +6,7 @@
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
     <%= vite_client_tag %>
+    <%= vite_react_refresh_tag %>
     <%= vite_javascript_tag 'application.tsx' %>
   </head>
 
diff --git a/projects/app/vite.config.ts b/projects/app/vite.config.ts
index 5148f81..7780972 100644
--- a/projects/app/vite.config.ts
+++ b/projects/app/vite.config.ts
@@ -4,6 +4,9 @@ import FullReload from "vite-plugin-full-reload";
 import ReactRefresh from "@vitejs/plugin-react-refresh";
 
 export default defineConfig({
+  define: {
+    'process.env.BUGSNAG_FRONTEND_KEY': JSON.stringify(process.env.BUGSNAG_FRONTEND_KEY),
+  },
   plugins: [
     RubyPlugin(),
     FullReload(["config/routes.rb", "app/views/**/*"]),
```

**Comment by pepibumur** [comment]
Hey @ElMassimo, thanks a lot for your support. I tried to follow the example that you shared, but the problem persists. I ended up opening [an issue](https://github.com/vitejs/vite/issues/3088) on the Vite repository as you suggested :).

**Comment by ElMassimo** [comment]
If you have time to dig a bit deeper and come up with a minimal reproduction of the issue, I'm sure the Vite team will appreciate that.

By the way, if you are looking for a simple way to setup sourcemaps in Bugsnag, check https://github.com/ElMassimo/vite-plugin-bugsnag.

**Comment by pepibumur** [comment]
> By the way, if you are looking for a simple way to setup sourcemaps in Bugsnag, check https://github.com/ElMassimo/vite-plugin-bugsnag.

This is damn awesome. You read what my next steps were.

**Pull request merged**
